[package]
name = "moonlink_service"
version.workspace = true
edition.workspace = true

[dependencies]
moonlink = { path = "../moonlink" }
moonlink_connectors = { path = "../moonlink_connectors" }
tokio.workspace = true

[dev-dependencies]
tokio-postgres.workspace = true