[package]
name = "pg_mooncake_test_fn"
version.workspace = true
edition.workspace = true

[dependencies]
moonlink_connectors = { path = "../moonlink_connectors" }
moonlink = { path = "../moonlink" }
pg_replicate.workspace = true
tokio.workspace = true
