[package]
name = "moonlink"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
pg_replicate.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
